package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS", catalog = "tpcw")
public class Address implements java.io.Serializable {

	private int addrId;
	private String addrStreet1;
	private String addrStreet2;
	private String addrCity;
	private String addrState;
	private String addrZip;
	private Integer addrCoId;

	public Address() {
	}

	public Address(int addrId) {
		this.addrId = addrId;
	}

	public Address(int addrId, String addrStreet1, String addrStreet2, String addrCity, String addrState,
			String addrZip, Integer addrCoId) {
		this.addrId = addrId;
		this.addrStreet1 = addrStreet1;
		this.addrStreet2 = addrStreet2;
		this.addrCity = addrCity;
		this.addrState = addrState;
		this.addrZip = addrZip;
		this.addrCoId = addrCoId;
	}

	@Id

	@Column(name = "ADDR_ID", unique = true, nullable = false)
	public int getAddrId() {
		return this.addrId;
	}

	public void setAddrId(int addrId) {
		this.addrId = addrId;
	}

	@Column(name = "ADDR_STREET1", length = 40)
	public String getAddrStreet1() {
		return this.addrStreet1;
	}

	public void setAddrStreet1(String addrStreet1) {
		this.addrStreet1 = addrStreet1;
	}

	@Column(name = "ADDR_STREET2", length = 40)
	public String getAddrStreet2() {
		return this.addrStreet2;
	}

	public void setAddrStreet2(String addrStreet2) {
		this.addrStreet2 = addrStreet2;
	}

	@Column(name = "ADDR_CITY", length = 30)
	public String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	@Column(name = "ADDR_STATE", length = 20)
	public String getAddrState() {
		return this.addrState;
	}

	public void setAddrState(String addrState) {
		this.addrState = addrState;
	}

	@Column(name = "ADDR_ZIP", length = 10)
	public String getAddrZip() {
		return this.addrZip;
	}

	public void setAddrZip(String addrZip) {
		this.addrZip = addrZip;
	}

	@Column(name = "ADDR_CO_ID")
	public Integer getAddrCoId() {
		return this.addrCoId;
	}

	public void setAddrCoId(Integer addrCoId) {
		this.addrCoId = addrCoId;
	}

}
