package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "AUTHOR", catalog = "tpcw")
public class Author implements java.io.Serializable {

	private int AId;
	private String AFname;
	private String ALname;
	private String AMname;
	private Date ADob;
	private String ABio;

	public Author() {
	}

	public Author(int AId) {
		this.AId = AId;
	}

	public Author(int AId, String AFname, String ALname, String AMname, Date ADob, String ABio) {
		this.AId = AId;
		this.AFname = AFname;
		this.ALname = ALname;
		this.AMname = AMname;
		this.ADob = ADob;
		this.ABio = ABio;
	}

	@Id

	@Column(name = "A_ID", unique = true, nullable = false)
	public int getAId() {
		return this.AId;
	}

	public void setAId(int AId) {
		this.AId = AId;
	}

	@Column(name = "A_FNAME", length = 20)
	public String getAFname() {
		return this.AFname;
	}

	public void setAFname(String AFname) {
		this.AFname = AFname;
	}

	@Column(name = "A_LNAME", length = 20)
	public String getALname() {
		return this.ALname;
	}

	public void setALname(String ALname) {
		this.ALname = ALname;
	}

	@Column(name = "A_MNAME", length = 20)
	public String getAMname() {
		return this.AMname;
	}

	public void setAMname(String AMname) {
		this.AMname = AMname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "A_DOB", length = 10)
	public Date getADob() {
		return this.ADob;
	}

	public void setADob(Date ADob) {
		this.ADob = ADob;
	}

	@Column(name = "A_BIO", length = 65535)
	public String getABio() {
		return this.ABio;
	}

	public void setABio(String ABio) {
		this.ABio = ABio;
	}

}
