package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "COUNTRY", catalog = "tpcw")
public class Country implements java.io.Serializable {

	private int coId;
	private String coName;
	private Double coExchange;
	private String coCurrency;

	public Country() {
	}

	public Country(int coId) {
		this.coId = coId;
	}

	public Country(int coId, String coName, Double coExchange, String coCurrency) {
		this.coId = coId;
		this.coName = coName;
		this.coExchange = coExchange;
		this.coCurrency = coCurrency;
	}

	@Id

	@Column(name = "CO_ID", unique = true, nullable = false)
	public int getCoId() {
		return this.coId;
	}

	public void setCoId(int coId) {
		this.coId = coId;
	}

	@Column(name = "CO_NAME", length = 50)
	public String getCoName() {
		return this.coName;
	}

	public void setCoName(String coName) {
		this.coName = coName;
	}

	@Column(name = "CO_EXCHANGE", precision = 22, scale = 0)
	public Double getCoExchange() {
		return this.coExchange;
	}

	public void setCoExchange(Double coExchange) {
		this.coExchange = coExchange;
	}

	@Column(name = "CO_CURRENCY", length = 18)
	public String getCoCurrency() {
		return this.coCurrency;
	}

	public void setCoCurrency(String coCurrency) {
		this.coCurrency = coCurrency;
	}

}
