package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS", catalog = "tpcw")
public class Orders implements java.io.Serializable {

	private int OId;
	private Integer OCId;
	private Date ODate;
	private Double OSubTotal;
	private Double OTax;
	private Double OTotal;
	private String OShipType;
	private Date OShipDate;
	private Integer OBillAddrId;
	private Integer OShipAddrId;
	private String OStatus;

	public Orders() {
	}

	public Orders(int OId) {
		this.OId = OId;
	}

	public Orders(int OId, Integer OCId, Date ODate, Double OSubTotal, Double OTax, Double OTotal, String OShipType,
			Date OShipDate, Integer OBillAddrId, Integer OShipAddrId, String OStatus) {
		this.OId = OId;
		this.OCId = OCId;
		this.ODate = ODate;
		this.OSubTotal = OSubTotal;
		this.OTax = OTax;
		this.OTotal = OTotal;
		this.OShipType = OShipType;
		this.OShipDate = OShipDate;
		this.OBillAddrId = OBillAddrId;
		this.OShipAddrId = OShipAddrId;
		this.OStatus = OStatus;
	}

	@Id

	@Column(name = "O_ID", unique = true, nullable = false)
	public int getOId() {
		return this.OId;
	}

	public void setOId(int OId) {
		this.OId = OId;
	}

	@Column(name = "O_C_ID")
	public Integer getOCId() {
		return this.OCId;
	}

	public void setOCId(Integer OCId) {
		this.OCId = OCId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "O_DATE", length = 10)
	public Date getODate() {
		return this.ODate;
	}

	public void setODate(Date ODate) {
		this.ODate = ODate;
	}

	@Column(name = "O_SUB_TOTAL", precision = 22, scale = 0)
	public Double getOSubTotal() {
		return this.OSubTotal;
	}

	public void setOSubTotal(Double OSubTotal) {
		this.OSubTotal = OSubTotal;
	}

	@Column(name = "O_TAX", precision = 22, scale = 0)
	public Double getOTax() {
		return this.OTax;
	}

	public void setOTax(Double OTax) {
		this.OTax = OTax;
	}

	@Column(name = "O_TOTAL", precision = 22, scale = 0)
	public Double getOTotal() {
		return this.OTotal;
	}

	public void setOTotal(Double OTotal) {
		this.OTotal = OTotal;
	}

	@Column(name = "O_SHIP_TYPE", length = 10)
	public String getOShipType() {
		return this.OShipType;
	}

	public void setOShipType(String OShipType) {
		this.OShipType = OShipType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "O_SHIP_DATE", length = 10)
	public Date getOShipDate() {
		return this.OShipDate;
	}

	public void setOShipDate(Date OShipDate) {
		this.OShipDate = OShipDate;
	}

	@Column(name = "O_BILL_ADDR_ID")
	public Integer getOBillAddrId() {
		return this.OBillAddrId;
	}

	public void setOBillAddrId(Integer OBillAddrId) {
		this.OBillAddrId = OBillAddrId;
	}

	@Column(name = "O_SHIP_ADDR_ID")
	public Integer getOShipAddrId() {
		return this.OShipAddrId;
	}

	public void setOShipAddrId(Integer OShipAddrId) {
		this.OShipAddrId = OShipAddrId;
	}

	@Column(name = "O_STATUS", length = 15)
	public String getOStatus() {
		return this.OStatus;
	}

	public void setOStatus(String OStatus) {
		this.OStatus = OStatus;
	}

}
