package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderLineId generated by hbm2java
 */
@Embeddable
public class OrderLineId implements java.io.Serializable {

	private int olId;
	private int olOId;

	public OrderLineId() {
	}

	public OrderLineId(int olId, int olOId) {
		this.olId = olId;
		this.olOId = olOId;
	}

	@Column(name = "OL_ID", nullable = false)
	public int getOlId() {
		return this.olId;
	}

	public void setOlId(int olId) {
		this.olId = olId;
	}

	@Column(name = "OL_O_ID", nullable = false)
	public int getOlOId() {
		return this.olOId;
	}

	public void setOlOId(int olOId) {
		this.olOId = olOId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderLineId))
			return false;
		OrderLineId castOther = (OrderLineId) other;

		return (this.getOlId() == castOther.getOlId()) && (this.getOlOId() == castOther.getOlOId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOlId();
		result = 37 * result + this.getOlOId();
		return result;
	}

}
