package data;
// Generated 31.05.2017 22:53:31 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderLine generated by hbm2java
 */
@Entity
@Table(name = "ORDER_LINE", catalog = "tpcw")
public class OrderLine implements java.io.Serializable {

	private OrderLineId id;
	private Integer olIId;
	private Integer olQty;
	private Double olDiscount;
	private String olComments;

	public OrderLine() {
	}

	public OrderLine(OrderLineId id) {
		this.id = id;
	}

	public OrderLine(OrderLineId id, Integer olIId, Integer olQty, Double olDiscount, String olComments) {
		this.id = id;
		this.olIId = olIId;
		this.olQty = olQty;
		this.olDiscount = olDiscount;
		this.olComments = olComments;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "olId", column = @Column(name = "OL_ID", nullable = false)),
			@AttributeOverride(name = "olOId", column = @Column(name = "OL_O_ID", nullable = false)) })
	public OrderLineId getId() {
		return this.id;
	}

	public void setId(OrderLineId id) {
		this.id = id;
	}

	@Column(name = "OL_I_ID")
	public Integer getOlIId() {
		return this.olIId;
	}

	public void setOlIId(Integer olIId) {
		this.olIId = olIId;
	}

	@Column(name = "OL_QTY")
	public Integer getOlQty() {
		return this.olQty;
	}

	public void setOlQty(Integer olQty) {
		this.olQty = olQty;
	}

	@Column(name = "OL_DISCOUNT", precision = 22, scale = 0)
	public Double getOlDiscount() {
		return this.olDiscount;
	}

	public void setOlDiscount(Double olDiscount) {
		this.olDiscount = olDiscount;
	}

	@Column(name = "OL_COMMENTS", length = 110)
	public String getOlComments() {
		return this.olComments;
	}

	public void setOlComments(String olComments) {
		this.olComments = olComments;
	}

}
